### ISSUE TITLE
[BUG] 新打开标签页的添加可能失败

### ISSUE THREAD

**Issue by Moyf** [gitcpy/obsidian-diagram-popup#10]
在打开一个新标签页的时候，可能无法给 Diagram 添加「pop up」特性：

详见视频（在沙盒仓库中测试）：
https://github.com/user-attachments/assets/753a53da-73a0-4abb-9d8c-0e7e20bdc21c

---

另一种情况是，如果编辑了 mermaid 代码块，重新渲染的时候，也无法添加特性：
![17c8480d-da0b-4432-8e5c-bbcb5dc89c42](https://github.com/user-attachments/assets/01c328be-3dc4-4b9b-bd4c-56eeef892679)

---

插件版本是 0.2.60
Obsidian 版本是 1.7.6

**Comment by gitcpy** [comment]
我稍后看看，谢谢反馈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-diagram-popup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 下午3:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gitcpy/obsidian-diagram-popup] [BUG] 新打开标签页的添加可能失败 (Issue #10)





 
在打开一个新标签页的时候，可能无法给 Diagram 添加「pop up」特性：
 
详见视频（在沙盒仓库中测试）：
 https://github.com/user-attachments/assets/753a53da-73a0-4abb-9d8c-0e7e20bdc21c
 
 
另一种情况是，如果编辑了 mermaid 代码块，重新渲染的时候，也无法添加特性：
 17c8480d-da0b-4432-8e5c-bbcb5dc89c42.gif (view on web)
 
 
插件版本是 0.2.60
 Obsidian 版本是 1.7.6

**Comment by gitcpy** [comment]
我查看了一下，确实存在你说的两种情况
但是我无法确认原因，具体是
1. ctrl+左键 新标签打开md文档，情况比较诡异，有概率无法添加弹窗按钮；
但是在左边文件浏览器右键菜单 新标签打开md文档都能添加弹窗按钮，没发现方法无法添加
2. 进入编辑状态，这个也诡异，之前我测试的是编辑后预览都能正常，也不知道产生的原因，
这个刚好概率相反，有一定概率正常添加如下视频所示：

https://github.com/user-attachments/assets/059495ee-77c6-4c61-8fbd-2980826c24a7

目前的解决办法是，你遇到这个情况，要么重开文档，要么就在 编辑模式 和 阅读模式 切换看看， 一般都会重新添加上

**Comment by gitcpy** [comment]
晕，又看了好几遍你的gif图。。。原来你在 dataview 里面用。。。。下次记得描述清楚，录清楚点。。。不然，还以为只是mermaid的问题，还好我仔细看，不过我这边错也错的刚好，看到 ob的 mermaid 本身有问题

**Comment by gitcpy** [comment]
我特地又尝试了下 dataview 下的 gantt 的 插件使用，我这边是正常的。。。

https://github.com/user-attachments/assets/ded603e5-8529-45d7-9897-d7cfae93010a

**Comment by gitcpy** [comment]
这个 obsidian 的 编辑模式 的 代码块 渲染预览，没有相关的事件，很难处理，官方也没有开源，能找到的 MarkdownPostProcessor 和 MarkdownCodeblockProcessor 也是语焉不详，经过测试是关于编辑后切换到阅读模式的事件，所以正常情况下，确实进入编辑状态退出后预览是没有的，并且也没有事件可以做处理，所以基本都是本人 靠ai和 自行测试 写的插件。。。非常无奈，最后用了一个不优雅的方法，observer监听。。。

**Comment by gitcpy** [comment]
更新到 0.2.62， 修复了 新开文档按钮可能丢失的bug，然后 编辑状态跟随这次更新没重现，你试试，有问题再留言

**Comment by gitcpy** [comment]
总的来说，这两个bug，更多的原因我推测是 obsidian 内部机制引起，你多试试。

**Comment by Moyf** [comment]
> 晕，又看了好几遍你的gif图。。。原来你在 dataview 里面用。。。。下次记得描述清楚，录清楚点，那个gif太快了，我特地录屏，慢放暂停看的。。。不然，还以为只是mermaid的问题，还好我仔细看，不过我这边错也错的刚好，看到 ob的 mermaid 本身有问题

啊，抱歉抱歉……
确实比较快，为了减少 gif 的体积所以压缩了时长，不然超过大小限制会无法上传

下次还有的话我就直接传视频吧~

**Comment by Moyf** [comment]
> 总的来说，这两个bug，更多的原因我推测是 obsidian 内部机制引起，你多试试。

比较奇怪的就是我之前用这个插件的时候，确实是没问题的
所以怀疑是不是 OB 更新了之后修改了一些机制，导致原来可行的方案现在失效了
（官方明确说了的是一个 Defer 机制，会延迟后台页面的加载）

我先更新试试看！

**Comment by gitcpy** [comment]
我的神，难怪了，你那里看到的，我去了解一下，谢谢交流！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-diagram-popup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月16日(星期六) 晚上11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-diagram-popup] [BUG] 新打开标签页的添加可能失败 (Issue #10)





  
总的来说，这两个bug，更多的原因我推测是 obsidian 内部机制引起，你多试试。
  
比较奇怪的就是我之前用这个插件的时候，确实是没问题的
 所以怀疑是不是 OB 更新了之后修改了一些机制，导致原来可行的方案现在失效了
 （官方明确说了的是一个 Defer 机制，会延迟后台页面的加载）
 
我先更新试试看！

**Comment by Moyf** [comment]
> 我的神，难怪了，你那里看到的，我去了解一下，谢谢交流！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gitcpy/obsidian-diagram-popup" ***@***.***&gt;; 发送时间:&nbsp;2024年11月16日(星期六) 晚上11:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gitcpy/obsidian-diagram-popup] [BUG] 新打开标签页的添加可能失败 (Issue #10) 总的来说，这两个bug，更多的原因我推测是 obsidian 内部机制引起，你多试试。 比较奇怪的就是我之前用这个插件的时候，确实是没问题的 所以怀疑是不是 OB 更新了之后修改了一些机制，导致原来可行的方案现在失效了 （官方明确说了的是一个 Defer 机制，会延迟后台页面的加载） 我先更新试试看！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

啊，我找给你，稍等——

说明文档在这里：
https://[docs.obsidian.md/Plugins/Guides/Understanding+deferred+views](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views)

**Comment by Moyf** [comment]
1.7 版本更新的时候添加的，如图：
![image](https://github.com/user-attachments/assets/7068820f-78f4-4ac6-946a-b628dad94703)

**Comment by gitcpy** [comment]
@Moyf 感谢，请问我们在一个qq群:427063403 吗？

**Comment by Moyf** [comment]
> @Moyf 感谢，请问我们在一个qq群:427063403 吗？

乐，不在~ 我可以加一下
