### ISSUE TITLE
[BUG] 插件商店异常

### ISSUE THREAD

**Issue by Moyf** [gitcpy/obsidian-diagram-popup#7]
在商店中看到的还是老的名字（Mermaid Pop），并且点击的时候会显示「Plugin ID mismatch」
![image](https://github.com/user-attachments/assets/34b07f40-5e61-41ee-b595-e8d637649510)

**Comment by gitcpy** [comment]
一言难尽，我本来是扩展了图表支持语言，然后改了名字，后来为了统一，顺便ID和名字一起改了提交官方，然后神奇的是官方审核一个月才告诉我说ID修改了用户会下载不了。这时我觉得功能扩展了，名字ID都变了，就重新找，重新下载吧。然后我又觉得不对劲，又问了一下，是不是可以改名字时，ID保持原来的就可以了。官方才回答是的。。。一个简单的修改和审核的沟通，我觉得官方的处理不及时，也说明不充分，导致耗时很久。你先在 brat 用这个安装 gitcpy/obsidian-diagram-popup， 我添加了 移动端触屏支持，你试试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-diagram-popup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月4日(星期一) 中午11:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gitcpy/obsidian-diagram-popup] [BUG] 插件商店异常 (Issue #7)





 
在商店中看到的还是老的名字（Mermaid Pop），并且点击的时候会显示「Plugin ID mismatch」
 image.png (view on web)

**Comment by gitcpy** [comment]
希望这次官方会快点通过，让大家能用到合适的插件

**Comment by gitcpy** [comment]
官方通过审核了，已经可以正常在插件社区下载了，你搜索 diagram popup 即可，感谢使用！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-diagram-popup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月4日(星期一) 中午11:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gitcpy/obsidian-diagram-popup] [BUG] 插件商店异常 (Issue #7)





 
在商店中看到的还是老的名字（Mermaid Pop），并且点击的时候会显示「Plugin ID mismatch」
 image.png (view on web)
